# Generated by Django 5.0.7 on 2024-07-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_list',
            name='image',
            field=models.ImageField(default=1, upload_to='images/blog'),
            preserve_default=False,
        ),
    ]
