# Generated by Django 5.0.7 on 2024-07-29 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='phone',
        ),
        migrations.AddField(
            model_name='teachers',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='courses.category'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], default='Senior', max_length=100),
        ),
    ]
